title = "Luanoid"

gitRepoUrl = "https://github.com/raphtalia/Luanoid"
gitSourceBranch = "main"

classOrder = [
  "Luanoid",
  "CharacterState",
  "CharacterController",
  "Animator",
]

[home]
enabled = true
includeReadme = true

[footer]
copyright = "Copyright © 2022 raphtalia"
