[package]
description = "Custom character system"
exclude = ["*"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]
license = "MIT"
name = "raphtalia/luanoid"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.3.3"

[dependencies]
EnumList = "sleitnick/enum-list@2.0.0"
Promise = "evaera/promise@3.2.1"
Signal = "sleitnick/signal@1.1.0"
TestEZ = "roblox/testez@0.4.1"
t = "osyrisrblx/t@3.0.0"

# [dev-dependencies]
# TestEZ = "roblox/testez@0.4.1"
