name: Selene

on:
    push:
        paths:
            - ".github/workflows/selene.yml"
            - "src/**"
            # - 'package.json'
    workflow_dispatch:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - uses: Roblox/setup-foreman@v1
              with:
                  version: "^1.0.0"
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run Selene
              run: selene src
